services:
  base-db:
    image: postgres:11.4
    command: postgres -c shared_buffers=512MB -c max_connections=500 -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  base-cache:
    image: redis:5.0.5
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s

  logspout:
    image: audius/logspout:v3.2.14-1
    container_name: logspout
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  filebeat:
    image: audius/filebeat:8.2.0
    container_name: filebeat
    user: root
    restart: always
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  metricbeat:
    image: audius/metricbeat:8.2.0
    container_name: metricbeat
    user: root
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
