services:
  base-db:
    image: postgres:11.4
    command: postgres -c shared_buffers=512MB -c max_connections=500 -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s

  base-cache:
    image: redis:5.0.5
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s

  logspout:
    image: gliderlabs/logspout:v3.2.14
    container_name: logspout
    environment:
      - SYSLOG_STRUCTURED_DATA=${LOGGLY_TOKEN}@41058 tag="logspout"
      - BACKLOG=false
    env_file:
      # requires audius-cli change
      - override.env
      # we can try both overrides and one SHOULD be empty and the other should have what we need
      - creator-node/override.env
      - discovery-provider/override.env
    command: multiline+syslog+tcp://logs-01.loggly.com:514
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
