services:
  base-db:
    image: postgres:11.4
    command: postgres -c shared_buffers=512MB -c max_connections=500 -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
    ports:
      - "5432:5432"

  base-cache:
    image: redis:5.0.5
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
