version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-6617985cc4b492cfd611a02ae27583c4f2dc986c}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
