version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-6a9f55801805c2abfb12288116c2ec5269822ebf}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
