version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-fbebfe4e4a5cfe93859e6e705051b5d4a258e61d}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
