version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-553bdce99f3b89c7e26f1ef96d6e68aaeba0d232}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
