version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-ca6e15e1379b72d88dd2a5ae1f5b6892a4d8d29e}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
