version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-bbadcdfdd596ae6c258369630cba9dafaaeb66e2}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
