version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-a695fa59b6a662c95719baa176157b2fa95b08c8}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
