version: "3.9"

services:
  dashboard:
    image: audius/dashboard:${TAG:-a514d746ed914821e9b193ac34d3fe344bd376e1}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - cn-network

networks:
  cn-network:
    name: creator-node_creator-node-network
    external: true
