up::
	npm run tsc && docker compose -f test-cluster.yml up --build

nuke::
	docker compose -f test-cluster.yml down --volumes


psql::
	docker exec -it czdb psql -U postgres cz1

sh::
	docker exec -it cz1 sh