services:
  czdb:
    container_name: czdb
    image: postgres
    ports:
      - '5454:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/create_dbs.sql:/docker-entrypoint-initdb.d/create_dbs.sql

  clusterizer1:
    container_name: cz1
    build: .
    command: pm2-runtime pm2.dev.config.cjs
    platform: 'linux/amd64'
    environment:
      audius_discprov_env: test
      HOST: clusterizer1
      audius_delegate_owner_wallet: '0x1c185053c2259f72fd023ED89B9b3EBbD841DA0F'
      audius_delegate_private_key: '293589cdf207ed2f2253bb72b17bb7f2cfe399cdc34712b1d32908d969682238'
      audius_db_url: 'postgresql://postgres:postgres@czdb:5432/cz1'
    ports:
      - 4222:4222
      - 6222:6222
      - 8925:8925
    volumes:
      - ./demo:/demo
      - ./scratch:/scratch
      - ./src:/app/src
      - data_cz1:/nats
    depends_on:
      - czdb

  clusterizer2:
    container_name: cz2
    build: .
    command: pm2-runtime pm2.dev.config.cjs
    platform: 'linux/amd64'
    depends_on:
      - czdb
    environment:
      audius_discprov_env: test
      HOST: clusterizer2
      audius_delegate_owner_wallet: '0x90b8d2655A7C268d0fA31758A714e583AE54489D'
      audius_delegate_private_key: '1ca1082d2304d96c2e6a3e551226e72e2cb54fddfe69b946b0efc2d9b43c19fc'
      audius_db_url: 'postgresql://postgres:postgres@czdb:5432/cz2'
    volumes:
      - ./src:/app/src
      - data_cz2:/nats

  clusterizer3:
    container_name: cz3
    build: .
    command: pm2-runtime pm2.dev.config.cjs
    platform: 'linux/amd64'
    depends_on:
      - czdb
    environment:
      audius_discprov_env: test
      HOST: clusterizer3
      audius_delegate_owner_wallet: '0xb7b9599EeB2FD9237C94cFf02d74368Bb2df959B'
      audius_delegate_private_key: '12712efcf90774399e272f8fc89ef264058b4cdd7f7f86956052050cbfb4350c'
      audius_db_url: 'postgresql://postgres:postgres@czdb:5432/cz3'
    volumes:
      - ./src:/app/src
      - data_cz3:/nats

volumes:
  data_cz1:
  data_cz2:
  data_cz3:
