version: "3.9"

services:
  notifications:
    image: audius/discovery-provider-notifications:${TAG:-fc9f4f8d0bece563a61747d295a81a4028117e40}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6000:6000"

  sla-auditor:
    image: audius/sla-auditor:${TAG:-fc9f4f8d0bece563a61747d295a81a4028117e40}
    container_name: sla-auditor
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

  dashboard:
    image: audius/dashboard:${TAG:-fc9f4f8d0bece563a61747d295a81a4028117e40}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - dn-network

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
