version: "3.9"

services:
  notifications:
    image: audius/discovery-provider-notifications:${TAG:-caa5d0bc66722804e597264b325dd89b4628728d}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6000:6000"

  sla-auditor:
    image: audius/sla-auditor:${TAG:-caa5d0bc66722804e597264b325dd89b4628728d}
    container_name: sla-auditor
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

  dashboard:
    image: audius/dashboard:${TAG:-caa5d0bc66722804e597264b325dd89b4628728d}
    container_name: dashboard
    restart: unless-stopped
    command: ["npm", "run", "start:${NETWORK:-prod}"]
    networks:
      - dn-network
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
