version: "3.9"

services:
  notifications:
    image: audius/discovery-provider-notifications:${TAG:-f0d7a571ca14703c97f8efdfb72c9d5dfa900b9f}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6000:6000"

  sla-auditor:
    image: audius/sla-auditor:${TAG:-f0d7a571ca14703c97f8efdfb72c9d5dfa900b9f}
    container_name: sla-auditor
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
