version: "3.9"

services:
  notifications:
    image: audius/discovery-provider-notifications:${TAG:-f03cb2d0e6b80b4740713831f87eff115ff920ed}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6000:6000"

  sla-auditor:
    image: audius/sla-auditor:${TAG:-f03cb2d0e6b80b4740713831f87eff115ff920ed}
    container_name: sla-auditor
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
