version: "3.9"

services:

  relay:
    image: audius/relay:${TAG:-014fcbd43047f33d734a418551c6d0429db07a7d}
    container_name: relay
    restart: unless-stopped
    networks:
      - dn-network
    environment:
      - ENVIRONMENT=${NETWORK}
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6001:6001"

  notifications:
    image: audius/discovery-provider-notifications:${TAG:-014fcbd43047f33d734a418551c6d0429db07a7d}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file
    ports:
      - "6000:6000"

  sla-auditor:
    image: audius/sla-auditor:${TAG:-014fcbd43047f33d734a418551c6d0429db07a7d}
    container_name: sla-auditor
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
