version: "3.9"

services:

  trending-challenge-rewards:
    image: audius/trending-challenge-rewards:${PEDALBOARD_TAG:-072dc096aec41803dcc6cab76961c2555bad7ed1}
    container_name: pedalboard-trending-challenge-rewards
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
      - pedalboard.env
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
