version: "3.9"

services:

  notifications:
    image: audius/discovery-provider-notifications:${NOTIFICATIONS_TAG:-3410f96241780a51125c15ea073035203c356d74}
    container_name: notifications
    restart: unless-stopped
    networks:
      - dn-network
    env_file:
      - ${NETWORK:-prod}.env
      - ${OVERRIDE_PATH:-override.env}
      - notifications.env
    logging:
      options:
        max-size: 10m
        max-file: 3
        mode: non-blocking
        max-buffer-size: 100m
      driver: json-file

networks:
  dn-network:
    name: discovery-provider_discovery-provider-network
    external: true
